# Generated by Django 5.1.1 on 2024-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=15)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('discount', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
